version: "3.1"
services:

  php:
    build: .docker/php
    container_name: ${PROJECT_NAME}-php
    working_dir: /application
    volumes:
      - .:/application
      - ./.docker/php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    ports:
      - "9000:9000"

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}-nginx
    working_dir: /application
    depends_on:
      - php
    volumes:
        - .:/application
        - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - .:/mysql/data
    ports:
      - "80:80"
    
  mysql:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}-mysql
    working_dir: /mysql/data
    volumes:
      - .:/application
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${PROJECT_NAME}-phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "81:80"

  mailhog:
    image: mailhog/mailhog
    container_name: ${PROJECT_NAME}-mailhog
    ports:
      - "82:8025"
      - "1025:1025"
